### ISSUE TITLE
Cannot find module 'react-native-crop-image' or its corresponding type declarations

### ISSUE THREAD

**Issue by sagarchavan491** [sudesh-kumar-cse/react-native-crop-images#1]
I am getting this error. when I tried to install the types, I was not able to install the types as well.

**Comment by sudesh-kumar-cse** [comment]
The issue has been resolved. It was caused by a configuration problem. I updated it and everything is working fine now. 
Can check [sagarchavan491](https://github.com/sagarchavan491)

**Comment by sudesh-kumar-cse** [comment]
The issue has been resolved. It was caused by a configuration problem. I updated it and everything is working fine now.
Can check [sagarchavan491](https://github.com/sagarchavan491)
